Декоративные элементы для главной.
htmlacademy-adaptive/907179-cat-energy-22 pull request #10
Opened 2021-04-29 18:46 UTC by dliferova

2021-04-30 08:33 UTC, undgrnd requested changes

2021-04-30 08:33 UTC, undgrnd commented on source/index.html
> +        <!--       <svg class="main-navigation__icon-menu" width="24" height="18">-->
Давай удалим если не нужно)

2021-04-30 08:33 UTC, undgrnd commented on source/index.html
> +                <img class="program-card__icon-1" src="img/program-icon-1-mobile.svg">
Такой нейминг не крутой) давай назовем функционально?

2021-04-30 08:33 UTC, undgrnd commented on source/index.html
> +                <div class="diet-totals-indicators-list__group-values diet-indicators-block">
diet-indicators-block — слово block можно всегда не писать, т.к. у нас тут везде блоки)

2021-04-30 08:33 UTC, undgrnd commented on source/sass/blocks/advantage-card.scss
> +  br {
Нельзя стилизовать теги)

2021-04-30 08:33 UTC, undgrnd commented on source/sass/blocks/advantage-card.scss
> +  br {
В разметке го решим без br)

2021-04-30 08:33 UTC, undgrnd commented on source/sass/blocks/copyright.scss
> +.footer__logo-image {
Не может в этом файле находиться

2021-04-30 08:33 UTC, undgrnd commented on source/sass/blocks/map.scss
> +    span {
Нельзя стилизовать теги, только классы)

2021-04-30 08:33 UTC, undgrnd commented on source/sass/blocks/range-demo-slider.scss
> +  .range-demo-slider {
Вот тут непонятно почему вдруг селекторы стали вкладываться в медиа выражения. Давай все везде переделаем чтобы медиа-выражения вкладывались в селекторы? 

Так читается гораздо-гораздо проще)

2021-04-30 08:33 UTC, undgrnd commented on source/sass/blocks/social.scss
> +  &:hover .social__link-icon_fb {
Из-за того что ты не пользуешься амперсандом вместо селектора вложенности, тебе приходиться дублировать :hover. Читать становиться тяжело(

Давай переделаем?

2021-04-30 08:33 UTC, undgrnd commented on source/sass/global/mixins.scss
> +@mixin action-style {
Для чего нужен такой миксин? Что он делает? Чисто по коду неясно

2021-05-02 13:02 UTC, dliferova commented on source/sass/global/mixins.scss
> +@mixin action-style {
Исправила

2021-05-02 13:02 UTC, dliferova commented on source/sass/blocks/social.scss
> +  &:hover .social__link-icon_fb {
Исправила

2021-05-02 13:02 UTC, dliferova commented on source/sass/blocks/range-demo-slider.scss
> +  .range-demo-slider {
Поправила

2021-05-02 13:02 UTC, dliferova commented on source/sass/blocks/copyright.scss
> +.footer__logo-image {
Убрала

2021-05-02 13:02 UTC, dliferova commented on source/sass/blocks/map.scss
> +    span {
Добавила класс

2021-05-02 13:02 UTC, dliferova commented on source/sass/blocks/advantage-card.scss
> +  br {
Дело в том, что именно в этом месте авторский перенос не получается решить другим способом - уменьшение ширины блока не помогает, если сделать так, чтобы ширина блока была по слово "наслаждайтесь", то хватает места и на слово "вашего" на след строке 
![CleanShot 2021-05-02 at 14 38 36](https://user-images.githubusercontent.com/53857604/116813509-5bc26080-ab54-11eb-88a2-35d3acb1a124.png)

2021-05-02 13:03 UTC, dliferova commented on source/index.html
> +                <img class="program-card__icon-1" src="img/program-icon-1-mobile.svg">
Исправила

2021-05-03 08:01 UTC, merged