Разметка страницы формы.
htmlacademy-adaptive/907179-cat-energy-22 pull request #3
Opened 2021-03-29 21:20 UTC by dliferova

Добавила разметку страницы формы + исправления главной страницы.

2021-03-30 08:16 UTC, mikhin requested changes

2021-03-30 08:16 UTC, mikhin commented on package-lock.json
> +  "name": "cat-energy-22",
Этот файл не должен был измениться, давай его уберем из ПР)

2021-03-30 08:16 UTC, mikhin commented on source/form.html
> +  <a class="page-header__logo-text cat-energy-text-icon">
Смущает БЭМ-блок `cat-energy-text-icon`, непонятно в чем его независимость, можно ли использовать его отдельно и если да то как

2021-03-30 08:16 UTC, mikhin commented on source/form.html
> +  <div class="choice-programs-content">
Давай в нейминге отвяжемся от текущего контента страницы и представим что контент может быть любой при том же дизайне)

2021-03-30 08:16 UTC, mikhin commented on source/form.html
> +    <form class="choice-programs-content__form programs-choice-form" action="https://echo.htmlacademy.ru" method="post">
Тоже и с формой — давай представим что те компоненты, которые мы разработаем, будут использоваться для самых разных форм и данных) т.е. нейминг должен быть абстрактный)

2021-03-30 08:16 UTC, mikhin commented on source/form.html
> +        <label class="pet-information-fields__label" for="name-field">Имя:*</label>
То же самое и про инпуты — они могут использоваться в проекте не только в контексте информации о питомце, значит нейминг должен быть абстрактный)

2021-04-01 10:06 UTC, mikhin commented on source/form.html
> +  <div class="form-content">
Чисто по коду непонятно что делает этот блок)

2021-04-01 10:07 UTC, mikhin commented on source/form.html
> +      <h1 class="form-description__title">Подбор программы</h1>
Вроде бы этот заголовок не относится к форме, но относится просто к странице? На странице каталога такой же заголовок будет)

2021-04-01 10:08 UTC, mikhin commented on source/form.html
> +    <form class="form-content__main-section form-partition" action="https://echo.htmlacademy.ru" method="post">
form-partition – не оч понятный нейминг)

2021-04-01 10:09 UTC, mikhin commented on source/form.html
> +        <input class="fieldset-section__input" type="text" name="name" id="name-field" placeholder="Барсик" required>
давай инпуты сделаем отдельным бэм-блоками?

2021-04-01 10:10 UTC, mikhin commented on source/form.html
> +          <p class="reminder-paragraph">*&mdash;Обязательные поля</p>
а вот эту штуку как раз лучше к форме привязать — ща по неймингу не оч понятно как это отдельно использовать)

2021-04-01 10:10 UTC, mikhin commented on source/form.html
> +          <button class="ordinary-button ordinary-button--submit" type="submit" value="Отправить форму">Отправить форму</button>
`ordinary-button` не оч понятный нейминг)

2021-04-01 10:10 UTC, mikhin commented on source/form.html
> +          <button class="ordinary-button ordinary-button--submit" type="submit" value="Отправить форму">Отправить форму</button>
ordinary-button--submit говорит о том, что независимый БЭМ-блок кнопки знает о месте своего употребления, а не должен хотеть. ему должно быть все равно где использоваться)

2021-04-01 11:52 UTC, dliferova commented on source/form.html
> +  <div class="form-content">
Используется, как блок-контейнер для контента на странице. Вот из этого комментария https://github.com/htmlacademy-adaptive/907179-cat-energy-22/pull/2#discussion_r602729443 поняла, что лучше не использовать wrapper, container

2021-04-01 11:52 UTC, dliferova commented on source/form.html
> +      <h1 class="form-description__title">Подбор программы</h1>
Исправлю)

2021-04-01 11:52 UTC, dliferova commented on source/form.html
> +    <form class="form-content__main-section form-partition" action="https://echo.htmlacademy.ru" method="post">
Заменю)

2021-04-01 11:52 UTC, dliferova commented on source/form.html
> +          <p class="reminder-paragraph">*&mdash;Обязательные поля</p>
Мне не очень понятна разница между этим элементом и инпутом из предидущего комментария. Надпись обязательные поля можно использовать в каком-нибудь popup регистрации пользователя, например. Но привязать его к форме втором классом, действительно нужно. А инпут как раз, по моему мнению, может быть внутри формы этой или другой, у него класс абстрактный, в любом случае он будет внутри fieldset.

2021-04-01 11:52 UTC, dliferova commented on source/form.html
> +          <button class="ordinary-button ordinary-button--submit" type="submit" value="Отправить форму">Отправить форму</button>
![image](https://user-images.githubusercontent.com/53857604/113288106-caf72b80-92ee-11eb-9414-958257837c9a.png) 
По БЭМ просто класс button не рекомендуют использовать, button нельзя привязать к цвету, остается только написать, что это _обычная кнопка_ (на которой будут стандартные стили размер шрифта, цвет текста и тд) + добавить модификатор о том, что это кнопка submit формы. Наверное, изменение ordinary на _common, standart_ не поможет. 

Если написать form-button, то на странице с каталогом придется эту кнопку снова делать БЭМ элементом. 

Получается, что остается пренебречь БЭМ документацией и сделать просто button

2021-04-01 11:52 UTC, dliferova commented on source/form.html
> +          <button class="ordinary-button ordinary-button--submit" type="submit" value="Отправить форму">Отправить форму</button>
_ordinary-button--submit говорит о том, что независимый БЭМ-блок кнопки знает о месте своего употребления_

![image](https://user-images.githubusercontent.com/53857604/113289298-4efde300-92f0-11eb-9716-d777c1f55894.png)

наверное, я не до конца понимаю модификаторы, но для меня --submit значит то, что я независимому БЭМ элементу модификатором добавляю состояние, необходимые для того, чтобы по модификатору было ясно, что эти стили нужны внутри формы и больше нигде

2021-04-03 19:19 UTC, mikhin approved these changes

2021-04-03 19:19 UTC, mikhin commented on source/form.html
> +    <section class="program-selection-section">
program-selection-section > program-selection-form =) так будет чуть более конкретней, что это именно форма)

2021-04-03 19:19 UTC, mikhin commented on source/form.html
> +        <fieldset class="form__fieldset fieldset-section">
абстракцию fieldset-section в данном случае можно упразднить и сделать все элементы от form, т.к. судя по названию и функционалу, кажется, fieldset-section нигде независимо не может использоваться, кроме как в форме)

2021-04-03 19:19 UTC, mikhin commented on source/form.html
> +            <input class="form-field__input form-input" type="text" name="name" id="name-field" placeholder="Барсик" required>
form-input > text-field или text-input, чтобы было более ясно, что это именно текстовое поле)

2021-04-03 19:19 UTC, mikhin commented on source/form.html
> +            <input class="form-field__input form-input" type="radio" name="goal" value="weightloss" id="weightloss-field" checked>
по идее это уже другой компонент, не `form-input`, т.к. это чекбокс и лучше сделать его отдельной абстракцией)

2021-04-03 19:19 UTC, merged