Выполнена базовая разметка страницы каталога.
htmlacademy-adaptive/907179-cat-energy-22 pull request #4
Opened 2021-04-04 17:35 UTC by dliferova

2021-04-05 08:04 UTC, mikhin requested changes

2021-04-05 08:04 UTC, mikhin commented on source/catalog.html
> +    <section class="catalog-main__section products-cards-section">
а products-cards-section для чего еще может быть независимо использован, если допустим не хотим в него products-list вкладывать?

2021-04-05 08:04 UTC, mikhin commented on source/catalog.html
> +          <h3 class="products-list__item-title product-card__title">Cat Energy PRO 500 г</h3>
смешивание на одной хтмл-ноде двух БЭМ-элементов — это всегда сложно и непонятно) давай упростим как-то?)

2021-04-05 08:04 UTC, mikhin commented on source/catalog.html
> +          <h3 class="products-list__item-title product-card__title">Cat Energy PRO 500 г</h3>
касается всех таких мест в коде)

2021-04-05 08:04 UTC, mikhin commented on source/catalog.html
> +          <table class="product-table__table-content">
Кажется что-то пошло не так, если у нас не все строчки в одной таблице, а в каждой таблице по одной строчке)

2021-04-05 08:04 UTC, mikhin commented on source/catalog.html
> +    <article class="catalog-main__aside-promotion special-offer-aside">
Для article маловато контента тут, имхо)

2021-04-05 08:04 UTC, mikhin commented on source/catalog.html
> +    <article class="catalog-main__aside-promotion special-offer-aside">
special-offer-aside – т.е. блок можно только как aside использовать?

2021-04-05 08:04 UTC, mikhin commented on source/catalog.html
> +        <li class="products-list__item product-card">
А могу попросить чисто ради эксперимента и прокачки именно на этой странице сделать по-другому для всех новых БЭМ-блоков, а именно — не миксовать блок и элемент на одной хтмл-ноде, а вкладывать блок в элемент?) Кажется, что код так будет проще читать гораздо)

2021-04-06 08:36 UTC, dliferova commented on source/catalog.html
> +    <article class="catalog-main__aside-promotion special-offer-aside">
Заменила. Не обратила внимание, что контент этой карточки напрямую связан с содержимым списка

2021-04-06 08:36 UTC, dliferova commented on source/catalog.html
> +        <li class="products-list__item product-card">
Исправила (+)

2021-04-06 08:36 UTC, dliferova commented on source/catalog.html
> +    <article class="catalog-main__aside-promotion special-offer-aside">
Исправила (+)

2021-04-06 08:37 UTC, dliferova commented on source/catalog.html
> +          <table class="product-table__table-content">
На десктопе выглядит как таблица =) немного перепутала, заменила на другой вариант

2021-04-06 08:37 UTC, dliferova commented on source/catalog.html
> +          <h3 class="products-list__item-title product-card__title">Cat Energy PRO 500 г</h3>
Исправила в main

2021-04-06 08:42 UTC, dliferova commented on source/catalog.html
> +      <ul class="products-cards-section__list products-list products-list--cards">
Пока не убирала модификаторы, но дала им другие названия. products-cards-section__list буду использоваться для позиционирования внутри страницы, products-list для общих стилей, а модификатор планирую использовать для стилей сетки, она у каждого списка будет своя.

2021-04-06 08:42 UTC, dliferova commented on source/catalog.html
> +    <div class="main-navigation__content">
Добавила в todo)

2021-04-06 13:32 UTC, mikhin approved these changes

2021-04-06 13:32 UTC, mikhin commented on source/catalog.html
> +      <a class="copyright__link" href="https://htmlacademy.ru/intensive/adaptive" aria-label="Перейти на сайт HTML Academy"></a>
Эта правка не для .editorconfig, а для stylelint. .editorconfig – это просто единый набор декларативных правил для всех редакторов, он сам ничего не проверяет и не ищет ошибки, он просто говорит как должно бы быть.

а вот stylelint — это уже линтер (проверятор) и он как раз уже ошибки)

2021-04-06 13:32 UTC, mikhin commented on source/catalog.html
> +      <ul class="catalog-main__products-list products-list products-list--full-cards">
Давай еще разделим catalog-main__products-list и products-list на разные хтмл-ноды? сейчас непонятно — семантика ul это чья из них ответственность?

2021-04-06 13:32 UTC, mikhin commented on source/catalog.html
> +            <dl class="product-full-card__description">
лайк за семантику)

2021-04-06 13:32 UTC, mikhin commented on source/catalog.html
> +          <div class="show-more-card">
Не очень понятно зачем в этой карточке две кнопки сразу)

2021-04-06 13:32 UTC, mikhin commented on source/catalog.html
> +      <ul class="catalog-main__products-list products-list products-list--brief-cards">
Давай еще может разделим списки на два отдельных БЭМ-блока и заодно избавимся от модификаторов? Сейчас пока не очень понятно, что общего по дизайну в этих списках и зачем для них делать общую абстракцию. Общее правило такое — лучше сделать две простых абстракции, чем одну сложную. Их проще понимать, использовать и рефакторить)

2021-04-06 13:32 UTC, mikhin commented on source/catalog.html
> +            <span class="product-brief-card__detail">1 упаковка (100 г)</span>
Это тоже походит на dt dl dd

2021-04-06 13:32 UTC, merged