Выполнена базовая стилизация главной страницы.
htmlacademy-adaptive/907179-cat-energy-22 pull request #5
Opened 2021-04-08 21:12 UTC by dliferova

2021-04-08 21:26 UTC, dliferova commented on package-lock.json
> +  "name": "cat-energy-22",
Я не меняла тут нэйм сама

2021-04-12 07:43 UTC, mikhin commented
before-mobile.png – непонятное имя файла

2021-04-12 07:58 UTC, mikhin requested changes

2021-04-12 07:58 UTC, mikhin commented on source/index.html
> +        <div class="programs-section__card">
Давай карточки сделаем отдельным БЭМ-блоком?

2021-04-12 07:58 UTC, mikhin commented on source/index.html
> +          <li class="advantages-section__item">
Давай эти карточки сделаем отдельным БЭМ-блоком?

2021-04-12 07:58 UTC, mikhin commented on source/index.html
> +          <span class="result-range__text">Было</span>
Давай поправим форматирование, чтобы элементы были вложены на один отступ?

2021-04-12 07:58 UTC, mikhin commented on source/index.html
> +<!--          Это временное p для того, чтобы изображение вело себя нормально-->
А нормально это как?)

2021-04-12 07:58 UTC, mikhin commented on source/index.html
> +          <img src="../img/before-mobile.png">
Нужен класс. Ни один элемент никогда не должен оставаться без класса, даже если не планируется этот класс использовать в CSS. Потому что классы — это атрибуты HTML прежде всего, во-первых, и во-вторых они улучшают читабельность кода)

2021-04-12 07:58 UTC, mikhin commented on source/index.html
> +      <div class="map__information-block">
information-block — не оч полезное имя, т.к. у нас тут все блоки и везде информация какая-то)

2021-04-12 07:58 UTC, mikhin commented on source/sass/blocks/advantages-section.scss
> +  @include resetting-styles-list;
лайк

2021-04-12 07:58 UTC, mikhin commented on source/sass/blocks/advantages-section.scss
> +.advantages-section__item:last-child {
давай унесем под амперсанд `&`?

2021-04-12 07:58 UTC, mikhin commented on source/sass/blocks/advertisment-section.scss
> +  background: url("../../img/index-can-mobile.png"), url("../../img/index-background-desktop.png");
непонятно зачем сразу два фона указывать

2021-04-12 07:58 UTC, mikhin commented on source/sass/blocks/advertisment-section.scss
> +  min-height: 437px;
если можно, то лучше заменить на внутренние отступы)

2021-04-12 07:58 UTC, mikhin commented on source/sass/blocks/advertisment-section.scss
> +    background: url("../../img/index-can-mobile.png"), url("../../img/index-background-desktop.png");
непонятно зачем два раза указывать + тут повторяется все тоже что было и выше зачем-то

2021-04-12 07:58 UTC, mikhin commented on source/sass/blocks/advertisment-section.scss
> +    font-weight: 400;
это можно занести в font-settings

2021-04-12 07:58 UTC, mikhin commented on source/sass/blocks/advertisment-section.scss
> +    @include font-settings(60px, 60px);
`font-settings` выглядит вроде бы удобно, но читабельность ухудшилась — остается только догадываться какие значения мы назначаем этими параметрами

2021-04-12 07:58 UTC, mikhin commented on source/sass/blocks/advertisment-section.scss
> +  @include primary-button-view;
такого рода миксины увеличивают связность проекта — код становится хрупче и непредсказуемее + теряется все преимущества БЭМа. Если мы хотим использовать первичную кнопку, мы должны явно использовать её прежде всего на уровне разметки.

2021-04-12 07:58 UTC, mikhin commented on source/sass/blocks/container.scss
> +    margin: 0 auto;
Мы не должны хотеть указывать на самом БЭМ-блоке правила внешней геометрии: margin, position: absolute, flex-grow, и т.д. Потому что это делает блок зависимым от места использования — а мы должен хотеть проектировать абсолютно-независимые БЭМ-блоки

2021-04-12 07:58 UTC, mikhin commented on source/sass/blocks/page-header.scss
> +    margin-bottom: 60px;
Мы не должны хотеть указывать на самом БЭМ-блоке правила внешней геометрии: margin, position: absolute, flex-grow, и т.д. Потому что это делает блок зависимым от места использования — а мы должен хотеть проектировать абсолютно-независимые БЭМ-блоки

2021-04-12 07:58 UTC, mikhin commented on source/sass/blocks/programs-section.scss
> +  margin-bottom: 20px;
Мы не должны хотеть указывать на самом БЭМ-блоке правила внешней геометрии: margin, position: absolute, flex-grow, и т.д. Потому что это делает блок зависимым от места использования — а мы должен хотеть проектировать абсолютно-независимые БЭМ-блоки

2021-04-12 07:58 UTC, mikhin commented on source/sass/global/mixins.scss
> +  #{font-size}: $font-size;
А зачем указывать в скобках названия свойств?

2021-04-12 07:58 UTC, mikhin commented on source/sass/global/mixins.scss
> +@mixin font-family-arial {
Миксин выглядит не оч полезным — занимает также одну строчку как и указание самого правила, но зато вносит неявность и делает явное неявным

2021-04-12 13:35 UTC, dliferova commented on source/index.html
> +  <link rel="stylesheet" href="sass/blocks/advantages-section.scss">
Какая-то ошибка, исправила.

2021-04-12 13:36 UTC, dliferova commented on source/index.html
> +      <img src="img/logo-mobile.svg" width="34" height="38" alt="Логотип кэт энерджи">
Добавила классы для img

2021-04-12 13:36 UTC, dliferova commented on source/index.html
> +        <div class="programs-section__card">
Cделала

2021-04-12 13:36 UTC, dliferova commented on source/index.html
> +          <li class="advantages-section__item">
Изменила

2021-04-12 13:36 UTC, dliferova commented on source/index.html
> +          <span class="result-range__text">Было</span>
Поправила

2021-04-12 13:36 UTC, dliferova commented on source/index.html
> +      <div class="map__information-block">
Исправила))

2021-04-12 13:36 UTC, dliferova commented on source/sass/blocks/advertisment-section.scss
> +  background: url("../../img/index-can-mobile.png"), url("../../img/index-background-desktop.png");
Подумала, что раз этот стаканчик не имеет смысла кроме декоративного => сделаю его вторым фоном. (Исправила это)

2021-04-12 13:36 UTC, dliferova commented on source/sass/blocks/advertisment-section.scss
> +    @include font-settings(60px, 60px);
Убрала

2021-04-12 13:36 UTC, dliferova commented on source/sass/blocks/advertisment-section.scss
> +  @include primary-button-view;
Да, тут странное решение, согласна

2021-04-12 13:37 UTC, dliferova commented on source/sass/blocks/container.scss
> +    margin: 0 auto;
Исправила

2021-04-12 13:37 UTC, dliferova commented on source/sass/blocks/page-header.scss
> +    margin-bottom: 60px;
Исправила, тут пропустила ошибку

2021-04-12 13:37 UTC, dliferova commented on source/sass/blocks/programs-section.scss
> +  margin-bottom: 20px;
Исправила

2021-04-12 13:37 UTC, dliferova commented on source/sass/global/mixins.scss
> +@mixin font-family-arial {
Исправила

2021-04-12 13:37 UTC, dliferova commented on source/index.html
> +<!--          Это временное p для того, чтобы изображение вело себя нормально-->
Вроде как в этом задании написано добавить фоновые цвета и фоновые изображения для блоков. В этом задании я добавила некоторые картинки, чтобы понять, где нужны отступы или контейнеры))

2021-04-12 13:40 UTC, dliferova commented
1) Убрала миксины для большей ясности в проекте
2) Добавила классы на элементы img 
3) Внесла правки в разметку (добавила 2 новых БЭМ блока) 
4) Поправила правило для внешней геометрии независимых блоков

2021-04-13 13:01 UTC, mikhin approved these changes

2021-04-13 13:01 UTC, merged