Выполнена стилизация страницы каталога.
htmlacademy-adaptive/907179-cat-energy-22 pull request #7
Opened 2021-04-18 18:03 UTC by dliferova

2021-04-18 18:24 UTC, undgrnd requested changes

2021-04-18 18:24 UTC, undgrnd commented on gulpfile.js
> +    open: false,
А это зачем?)

2021-04-18 18:24 UTC, undgrnd commented on source/catalog.html
> +  <link rel="icon" href="img/favicon/favicon.svg">
Непонятно почему не все favicon лежат в одной директории)

2021-04-18 18:24 UTC, undgrnd commented on source/catalog.html
> +    <nav class="page-header__navigation main-navigation main-navigation_closed main-navigation_theme_light_background">
main-navigation_theme_light_background – по БЭМ не может быть такого именования, т.к. может быть только один "ключ" и только одно "значение")

2021-04-18 18:24 UTC, undgrnd commented on source/catalog.html
> +  <div class="catalog-main__container catalog-main__container_for_mobile">
> catalog-main__container_for_mobile

вот это прям залет 😅 расскажешь для чего нужно?)

2021-04-18 18:24 UTC, undgrnd commented on source/catalog.html
> +            <button class="product-full-card__button button button--primary">Заказать</button>
> button--primary

Нужно выбрать и использовать во всем проекте какую-то одну нотацию, чтобы было единообразие)

2021-04-18 18:24 UTC, undgrnd commented on source/catalog.html
> +            <div class="show-more-card__plus-icon"></div>
Не должно висеть декоративных тегов в разметке — давай унесем в CSS?

2021-04-18 18:24 UTC, undgrnd commented on source/catalog.html
> +    <h2 class="page__subtitle page__subtitle_decorated catalog-main__subtitle">Дополнительные товары</h2>
> page__subtitle_decorated

не очень удачное имя, потому что непонятное

2021-04-18 18:24 UTC, undgrnd commented on source/catalog.html
> +    <h2 class="page__subtitle page__subtitle_decorated catalog-main__subtitle">Дополнительные товары</h2>
Смущает что на одном HTML-узле висят элементы от разных БЭМ-блоков, зачем такое нужно?

2021-04-18 18:24 UTC, undgrnd commented on source/sass/blocks/catalog-main.scss
> +    margin: 0 auto;
Правила в медиа-выражениях наследуются по каскаду, так что в данном случае получается дублирование уже вышеобъявленного правила

2021-04-18 18:24 UTC, undgrnd commented on source/sass/blocks/catalog-main.scss
> +.catalog-main__container_for_mobile {
скорее всего нужно удалить) или переименовать

2021-04-18 18:24 UTC, undgrnd commented on source/sass/blocks/main-navigation.scss
> +.main-navigation_theme_dark_background .main-navigation__item-content {
Вот тут как раз вместо селектора вложенности будет читабельнее использовать амперсанд

2021-04-18 18:24 UTC, undgrnd commented on source/sass/blocks/page.scss
> +.page__subtitle_decorated::after {
Для псевдоэлементов и псевдоселекторов тоже будет лучше использовать амперсанд

2021-04-18 18:24 UTC, undgrnd commented on source/sass/blocks/product-brief-card.scss
> +
Лишняя строка)

2021-04-18 18:24 UTC, undgrnd commented on source/sass/blocks/product-full-card.scss
> +    margin: -50px 0 34px;
Подозрительный отрицательный отступ) зачем нужен?)

2021-04-18 18:24 UTC, undgrnd commented on source/sass/blocks/products-brief-cards-list.scss
> +.products-brief-cards-list__item:last-child {
Лучше убрать под амперсанд)

2021-04-18 18:24 UTC, undgrnd commented on source/sass/blocks/show-more-card.scss
> +.show-more-card__plus-icon::before {
Лучше убрать под амперсанд)

2021-04-18 18:24 UTC, undgrnd commented on source/sass/style.scss
> +//Catalog page
Исходя из идеологии БЭМ, мы не должны хотеть разделять блоки по страницам использования, потому что мы как раз проектируем блоки просто как библиотеку компонентов, которые могут использоваться где угодно и как угодно)

Давай удалим комменты и отсортируем в алфавитном порядке?)

2021-04-18 18:45 UTC, dliferova commented on gulpfile.js
> +    open: false,
Чтобы браузер не открывался самостоятельно. У меня по умолчанию стоит сафари, а инспекчу я в хром/файрфокс

2021-04-18 18:47 UTC, dliferova commented on source/catalog.html
> +  <link rel="icon" href="img/favicon/favicon.svg">
favicon.ico должен в корне проекта ведь лежать. На первом курсе, по крайней мере, я точно делала в разных директориях

2021-04-18 18:56 UTC, dliferova commented on source/sass/blocks/catalog-main.scss
> +.catalog-main__container_for_mobile {
ошибочно затесался, это был пробный вариант "для себя"

2021-04-18 19:01 UTC, dliferova commented on source/sass/style.scss
> +//Catalog page
Пока мне удобно было делать так, потому что на данном этапе я работала в разных ветках одновременно и это помогало избегать лишних конфликтов.

2021-04-18 19:02 UTC, dliferova commented on source/sass/blocks/product-full-card.scss
> +    margin: -50px 0 34px;
Чтобы картинка вышла за пределы карточки

2021-04-18 19:14 UTC, dliferova commented on source/catalog.html
> +    <h2 class="page__subtitle page__subtitle_decorated catalog-main__subtitle">Дополнительные товары</h2>
На странице формы есть подобные элементы - заголовки fieldset, поэтому
1. у нас есть элементы page__subtitle, на них вешаем размеры текста и то, что касается внешнего вида
2. Нам нужен модификатор для того, чтобы мы могли добавить зеленые полоски по бокам (и если честно, нет идей пока как его переименовать, потому что модификатор должен отображать функцию, вот он ее и отображает - декоративные элементы для subtitle) 
3. Мы переиспользовали элементы, но на каждой странице у них разные могут быть margin (с пиксель перфект - так точно), поэтому сделала этот заголовок еще и ребенком на конкретно этой странице. 

Если этот заголовок сделать отдельным блоком (которому опять же нельзя задать внешнюю геометрию) это вроде не спасает

Пока такие размышления, попробую улучшить

2021-04-18 19:18 UTC, dliferova commented on source/catalog.html
> +  <div class="catalog-main__container catalog-main__container_for_mobile">
Пыталась решить проблему с тем, что на мобильной версии у секции с каталогом карточек слева и справа отступа нет, а у секции дополнительные товары есть

2021-04-19 09:37 UTC, dliferova commented
Исправила: 
1. Выбрала одну нотацию и поправила элементы, относящиеся к каталогу
2. Убрала лишний контейнер для мобильных устройств. 
3. Заменила использование & для комбинации селекторов
4. Убрала из разметки декоративный элемент (перенесу в css на задании по декоративным элементам
5. Изменила название класса page__subtitle на более понятный

2021-04-19 12:51 UTC, undgrnd commented on source/sass/style.scss
> +//Catalog page
Окей)

2021-04-19 12:55 UTC, undgrnd commented on source/sass/blocks/main-navigation.scss
> +  &_active {
@dliferova , хоть критерии такое и разрешают, в реальных проектах не советую делить именно имя класса амперсандом. Псевдоэлементы, псевдоселекторы, отношения между классами — да, нужно убирать под амперсанд, а вот дробить имя класса — нет. Это ухудшает читабельность кода в проекте, например, такое имя класса становится невозможным найти через поиск ctrl + f.

2021-04-19 12:55 UTC, undgrnd approved these changes

2021-04-19 12:55 UTC, merged