Сетки для главной страницы.
htmlacademy-adaptive/907179-cat-energy-22 pull request #8
Opened 2021-04-20 10:03 UTC by dliferova

2021-04-21 08:10 UTC, undgrnd requested changes

2021-04-21 08:10 UTC, undgrnd commented on source/index.html
> +        <div class="range">
Однословное имя класса — не оч

2021-04-21 08:10 UTC, undgrnd commented on source/index.html
> +        <div class="range">
Давай весь range разделим на несколько БЭМ-блоков, сейчас он очень жирный

2021-04-21 08:10 UTC, undgrnd commented on source/sass/blocks/advantage-card.scss
> +.advantage-card::before {
под амперсанд

2021-04-21 08:10 UTC, undgrnd commented on source/sass/blocks/advertisment-section.scss
> +  // TODO Продумать, чтобы картинка фона выглядела нормально до tablet версии, а не только на 320
обычно тогда на мобиле показывают сразу планшетную картинку, чтобы она норм тянулась от 320 до 768 и качество не падало

2021-04-21 08:10 UTC, undgrnd commented on source/sass/blocks/main-navigation.scss
> +.main-navigation_theme_dark .main-navigation__item-content {
давай всегда селектор вложенности делать через амперсанд?

2021-04-21 08:10 UTC, undgrnd commented on source/sass/blocks/main-navigation.scss
> +.main-navigation_theme_dark .main-navigation__item-content:hover {
тут нужно два амперсанда)

2021-04-21 08:10 UTC, undgrnd commented on source/sass/blocks/main-navigation.scss
> +.main-navigation_theme_dark .main-navigation__item-content:hover {
короче касается всех этих мест тут рядом)

2021-04-21 08:10 UTC, undgrnd commented on source/sass/blocks/page-main.scss
> +  //TODO что можно сделать вместо этой конструкции
не понял?

2021-04-21 08:10 UTC, undgrnd commented on source/sass/blocks/range.scss
> +.range__group-final-values_with-border {
неудачный нейминг модификатора

2021-04-21 08:10 UTC, undgrnd commented on source/sass/blocks/range.scss
> +.range__group-final-values_with-border {
кстати различный вид этого контрола на мобильных и десктопах — это два разных бэм блока, я считаю

2021-04-21 18:58 UTC, dliferova commented on source/index.html
> +        <div class="range">
не такой уж с этим БЭМ и "быстрый старт" ;((

2021-04-21 18:58 UTC, dliferova commented on source/sass/blocks/page-main.scss
> +  //TODO что можно сделать вместо этой конструкции
Не очень нравятся такие большие margin и padding в дестопной версии

2021-04-21 18:58 UTC, dliferova commented on source/sass/blocks/range.scss
> +.range__group-final-values_with-border {
Модификатор может отражать состояние, поведение, характеризовать внешний вид. В документации есть пример вот такого модификатора 

![CleanShot 2021-04-21 at 20 43 25](https://user-images.githubusercontent.com/53857604/115604951-3d519f00-a2e2-11eb-86db-437ca827dc23.png)

Не понимаю, в чем именно неудачность моего модификатора))) группа - значений - рэнжа - с рамкой. Просто функционально этот блок не отличается от блока затраты на питание, их отличие - только декоративное,  почему модификатор _size-small - норм, а  _with-border нет

2021-04-21 18:58 UTC, dliferova commented on source/sass/blocks/range.scss
> +.range__group-final-values_with-border {
![CleanShot 2021-04-21 at 20 29 06](https://user-images.githubusercontent.com/53857604/115603268-3f1a6300-a2e0-11eb-8e47-38cf70778fb3.png)

эти три блока ведь находятся внутри одного dl = семантически обозначают одно и тоже показатель-значение, только два декорированы рамкой серой, а один написан в строчку. Разве тут не лучше сделать модификатор?
Я отталкиваюсь от того, что "блок можно переиспользовать в проекте", не знаю, где отдельно можно переиспользовать блок такой.

![CleanShot 2021-04-21 at 20 36 47](https://user-images.githubusercontent.com/53857604/115604135-50b03a80-a2e1-11eb-99ee-ca621a48409b.png)

2021-04-22 09:30 UTC, dliferova commented on source/sass/blocks/main-navigation.scss
> +.main-navigation_theme_dark .main-navigation__item-content {
А это подходит для критерия Д11? _ Родительский селектор & используется только для псевдоэлементов, псевдоклассов и модификаторов.._

2021-04-22 09:48 UTC, dliferova commented
Внесла доработки в секцию с range. Исправила амперсанд для псевдоэлемента before. Селектор вложенности исправлю ближе к финальной части.

2021-04-22 11:43 UTC, undgrnd commented on source/sass/blocks/main-navigation.scss
> +.main-navigation_theme_dark .main-navigation__item-content {
Я думаю, что да

2021-04-22 11:45 UTC, undgrnd commented on source/sass/blocks/range.scss
> +.range__group-final-values_with-border {
> эти три блока ведь находятся внутри одного dl = семантически обозначают одно и тоже показатель-значение, только два декорированы рамкой серой, а один написан в строчку. Разве тут не лучше сделать модификатор?

неа) потому что в случае с отдельными БЭМ-блоками — это просто отдельные БЭМ-блоки, их исходный код очень просто читать и использовать) а в случае с единым блоком — придется одно костылить и подгонять под другое, исходный код читать сложно + переиспользуемость падает.

2021-04-22 11:47 UTC, undgrnd commented on source/sass/blocks/range.scss
> +.range__group-final-values_with-border {
> Я отталкиваюсь от того, что "блок можно переиспользовать в проекте", не знаю, где отдельно можно переиспользовать блок такой.

ты и не должна заранее знать, где и что как в будущем будет использовать, но как _архитектор_ ты должна закладывать в свою систему такую возможность — повсеместного использования блоков в будущем и возможность составления других композиций из текущих блоков

2021-04-22 11:48 UTC, undgrnd commented on source/sass/blocks/range.scss
> +.range__group-final-values_with-border {
@dliferova , кстати я неправильно указал селектор для своего первоначально коммента. я имел ввиду, что не эти факты разные БЭМ-блоки на мобильных и десктопках, а именно слайдер переключения "до и после"

2021-04-22 16:51 UTC, dliferova commented on source/sass/blocks/range.scss
> +.range__group-final-values_with-border {
в предложенных символах нет подходящей реакции
![1581475617125482694](https://user-images.githubusercontent.com/53857604/115753500-8b76a900-a39b-11eb-8173-3efb89bb3447.jpg)

2021-04-26 09:35 UTC, undgrnd approved these changes

2021-04-26 09:35 UTC, merged