Выполнены адаптивные сетки для страницы формы.
htmlacademy-adaptive/907179-cat-energy-22 pull request #9
Opened 2021-04-26 10:08 UTC by dliferova

1) Добавлены сетки.
2) Добавлена google-карта.

2021-04-26 10:18 UTC, undgrnd commented
@dliferova , контейнер должен сохраняться и для названий секций, они не должны уезжать к краям экрана)

<img width="1271" alt="Screenshot 2021-04-26 at 13 17 44" src="https://user-images.githubusercontent.com/19710346/116067501-db05ef00-a691-11eb-874e-9f344f33d3bd.png">

2021-04-27 18:58 UTC, undgrnd requested changes

2021-05-03 19:33 UTC, dliferova commented
Правки по комментариям в коммите "Добавлена стилизация декоративных элементов. Правки адаптивные сетки".

2021-05-04 16:19 UTC, mikhin approved these changes

2021-05-04 16:19 UTC, mikhin commented on source/sass/blocks/additional-fieldset.scss
> +  :last-child {
А тут амперсанд не нужен разве?

2021-05-04 16:19 UTC, merged